### ISSUE TITLE
Cannot install pre-built binary on windows

### ISSUE THREAD

**Issue by ketanhdoshi** [kelektiv/node.bcrypt.js#487]
Thanks for reporting a new issue with the node bcrypt module!

To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem
* Make sure you have installed the required dependencies listed on the readme
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

* What went wrong?
Got the following error when installing on Windows

d:\dev> npm install bcrypt --save

> bcrypt@1.0.2 install D:\KD Files\Dev\react\hapi-mongo\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcryp
t.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@6.9.1 (
node-v48 ABI) (falling back to source compile with node-gyp)

* What did you expect to happen?
This is similar to #476, but I do not want to compile from source. I want to download the pre-built binaries but the link is incorrect. It seems that you could replace this link: [https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-win32-x64.tar.gz](url)
 with this one: [https://github.com/kelektiv/node.bcrypt.js/archive/v1.0.2.zip](url)

* Which version of nodejs and OS?
Node 6.91 and Windows 8.1

* If you find a bug, please write a failing test.

Thanks!

P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation. Sorry, but there are just too many issues opened with no useful information or questions which have been previously addressed.

**Comment by Agathver** [comment]
This issue should be addressed by #470 
For windows support please help with the related PR #483. It requires a PowerShell Script to automate uploading the release compiled in AppVeyor. See .trayis.yml for a bash script that does the same.

**Comment by michelgokan** [comment]
Added a pull request. Fixed my problem https://github.com/kelektiv/node.bcrypt.js/pull/489

**Comment by michelgokan** [comment]
I just added a pull request, this fixed my problem: https://github.com/kelektiv/node.bcrypt.js/pull/489

**Comment by defunctzombie** [comment]
@michelgokan How did #489 PR solve your problem? It still does not have any of the binaries at that location.

**Comment by antwal** [comment]
@ketanhdoshi I have tried it on Windows 10, working without problems:

Install NodeJS latest version (i have used 6.9.5)
Run powershell with administrator privileges
Install build tools: 
`npm install --global --production windows-build-tools`

now can install bcrypt without error.

**Comment by defunctzombie** [comment]
I have uploaded the latest binaries to github. Please try to install on windows again and close this issue if the issue is resolved.

**Comment by devKC** [comment]
I am also having this issue, for me it's deploying to Heroku. Running node v6.10.10 npm v4.3.0. What can I try to troubleshoot around this?

**Comment by Agathver** [comment]
Windows binaries have been updated to the latest published version
